"""add_user_enhancements_and_user_sessions

Revision ID: 94ab85f4bf75
Revises: bc3d261dda6a
Create Date: 2026-04-11 19:55:42.622856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ab85f4bf75'
down_revision: Union[str, Sequence[str], None] = 'bc3d261dda6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_session_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cards_reviewed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_quality', sa.Float(), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_groups_started', 'study_session_groups', ['started_at'], unique=False)
    op.create_index('idx_session_groups_user', 'study_session_groups', ['user_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), server_default='#3B82F6', nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_topics_user', 'topics', ['user_id'], unique=False)
    op.create_index('idx_topics_user_slug', 'topics', ['user_id', 'slug'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_sessions_active', 'user_sessions', ['user_id', 'is_revoked'], unique=False)
    op.create_index('idx_user_sessions_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_user_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.create_table('document_topics',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'document_id')
    )
    op.create_index('idx_document_topics_document', 'document_topics', ['document_id'], unique=False)
    op.create_index('idx_document_topics_topic', 'document_topics', ['topic_id'], unique=False)
    op.create_table('note_topics',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'note_id')
    )
    op.create_index('idx_note_topics_note', 'note_topics', ['note_id'], unique=False)
    op.create_index('idx_note_topics_topic', 'note_topics', ['topic_id'], unique=False)
    op.add_column('study_sessions', sa.Column('group_id', sa.UUID(), nullable=True))
    op.create_index('idx_study_sessions_group', 'study_sessions', ['group_id'], unique=False)
    op.create_foreign_key(None, 'study_sessions', 'study_session_groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'study_sessions', type_='foreignkey')
    op.drop_index('idx_study_sessions_group', table_name='study_sessions')
    op.drop_column('study_sessions', 'group_id')
    op.drop_index('idx_note_topics_topic', table_name='note_topics')
    op.drop_index('idx_note_topics_note', table_name='note_topics')
    op.drop_table('note_topics')
    op.drop_index('idx_document_topics_topic', table_name='document_topics')
    op.drop_index('idx_document_topics_document', table_name='document_topics')
    op.drop_table('document_topics')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index('idx_user_sessions_user', table_name='user_sessions')
    op.drop_index('idx_user_sessions_expires', table_name='user_sessions')
    op.drop_index('idx_user_sessions_active', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('idx_topics_user_slug', table_name='topics')
    op.drop_index('idx_topics_user', table_name='topics')
    op.drop_table('topics')
    op.drop_index('idx_session_groups_user', table_name='study_session_groups')
    op.drop_index('idx_session_groups_started', table_name='study_session_groups')
    op.drop_table('study_session_groups')
    # ### end Alembic commands ###
