"""obsidian_graph_integration

Revision ID: a3d7eef3ffed
Revises: h5i6j7k8l9m0
Create Date: 2026-04-10 21:10:05.366247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3d7eef3ffed'
down_revision: Union[str, Sequence[str], None] = 'h5i6j7k8l9m0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('idx_document_chunks_chunk_index'), table_name='document_chunks')
    op.drop_index(op.f('idx_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('idx_documents_user_id'), table_name='documents')
    op.alter_column('entity_aliases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('entity_aliases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_entity_aliases_alias'), table_name='entity_aliases')
    op.drop_index(op.f('idx_entity_aliases_user_id'), table_name='entity_aliases')
    op.create_index(op.f('ix_entity_aliases_alias_name'), 'entity_aliases', ['alias_name'], unique=False)
    op.create_index(op.f('ix_entity_aliases_canonical_name'), 'entity_aliases', ['canonical_name'], unique=False)
    op.alter_column('flashcards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('flashcards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_flashcards_document_id'), table_name='flashcards')
    op.add_column('graph_entities', sa.Column('source', sa.String(length=50), server_default='ai_extracted', nullable=False))
    op.add_column('graph_entities', sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('graph_entities', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('graph_entities', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_index(op.f('idx_graph_entities_canonical_name'), table_name='graph_entities')
    op.drop_index(op.f('idx_graph_entities_document_id'), table_name='graph_entities')
    op.drop_index(op.f('idx_graph_entities_type'), table_name='graph_entities')
    op.create_index('idx_graph_entities_tags', 'graph_entities', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_graph_entities_source'), 'graph_entities', ['source'], unique=False)
    op.add_column('graph_relations', sa.Column('source', sa.String(length=50), server_default='ai_extracted', nullable=False))
    op.add_column('graph_relations', sa.Column('is_backlink', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('graph_relations', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.alter_column('graph_relations', 'relation_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.drop_index(op.f('idx_graph_relations_document_id'), table_name='graph_relations')
    op.drop_index(op.f('idx_graph_relations_source_id'), table_name='graph_relations')
    op.drop_index(op.f('idx_graph_relations_target_id'), table_name='graph_relations')
    op.drop_index(op.f('idx_graph_relations_type'), table_name='graph_relations')
    op.create_index(op.f('ix_graph_relations_source'), 'graph_relations', ['source'], unique=False)
    op.create_index(op.f('ix_graph_relations_source_entity_id'), 'graph_relations', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_graph_relations_target_entity_id'), 'graph_relations', ['target_entity_id'], unique=False)
    op.drop_index(op.f('idx_messages_conversation_id'), table_name='messages')
    op.add_column('note_links', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('note_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_note_links_source_target'), 'note_links', type_='unique')
    op.create_index('uq_note_links_source_target', 'note_links', ['source_note_id', 'target_note_id'], unique=True)
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_notes_user_created'), table_name='notes')
    op.create_index('idx_notes_user_type', 'notes', ['user_id', 'note_type'], unique=False)
    op.add_column('quiz_answers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('quiz_answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('quiz_results', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('quiz_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_quiz_results_user_completed'), table_name='quiz_results')
    op.alter_column('quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quizzes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('study_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('study_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_study_sessions_idempotency_key'), table_name='study_sessions')
    op.create_index(op.f('ix_study_sessions_idempotency_key'), 'study_sessions', ['idempotency_key'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_study_sessions_idempotency_key'), table_name='study_sessions')
    op.create_index(op.f('idx_study_sessions_idempotency_key'), 'study_sessions', ['idempotency_key'], unique=False)
    op.alter_column('study_sessions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('study_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quizzes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quizzes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_quiz_results_user_completed'), 'quiz_results', ['user_id', 'completed_at'], unique=False)
    op.alter_column('quiz_results', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('quiz_results', 'updated_at')
    op.alter_column('quiz_answers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('quiz_answers', 'updated_at')
    op.drop_index('idx_notes_user_type', table_name='notes')
    op.create_index(op.f('idx_notes_user_created'), 'notes', ['user_id', 'created_at'], unique=False)
    op.alter_column('notes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('uq_note_links_source_target', table_name='note_links')
    op.create_unique_constraint(op.f('uq_note_links_source_target'), 'note_links', ['source_note_id', 'target_note_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('note_links', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('note_links', 'updated_at')
    op.create_index(op.f('idx_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_graph_relations_target_entity_id'), table_name='graph_relations')
    op.drop_index(op.f('ix_graph_relations_source_entity_id'), table_name='graph_relations')
    op.drop_index(op.f('ix_graph_relations_source'), table_name='graph_relations')
    op.create_index(op.f('idx_graph_relations_type'), 'graph_relations', ['relation_type'], unique=False)
    op.create_index(op.f('idx_graph_relations_target_id'), 'graph_relations', ['target_entity_id'], unique=False)
    op.create_index(op.f('idx_graph_relations_source_id'), 'graph_relations', ['source_entity_id'], unique=False)
    op.create_index(op.f('idx_graph_relations_document_id'), 'graph_relations', ['document_id'], unique=False)
    op.alter_column('graph_relations', 'relation_type',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('graph_relations', 'metadata')
    op.drop_column('graph_relations', 'is_backlink')
    op.drop_column('graph_relations', 'source')
    op.drop_index(op.f('ix_graph_entities_source'), table_name='graph_entities')
    op.drop_index('idx_graph_entities_tags', table_name='graph_entities', postgresql_using='gin')
    op.create_index(op.f('idx_graph_entities_type'), 'graph_entities', ['entity_type'], unique=False)
    op.create_index(op.f('idx_graph_entities_document_id'), 'graph_entities', ['document_id'], unique=False)
    op.create_index(op.f('idx_graph_entities_canonical_name'), 'graph_entities', ['canonical_name'], unique=False)
    op.drop_column('graph_entities', 'metadata')
    op.drop_column('graph_entities', 'file_path')
    op.drop_column('graph_entities', 'tags')
    op.drop_column('graph_entities', 'source')
    op.create_index(op.f('idx_flashcards_document_id'), 'flashcards', ['document_id'], unique=False)
    op.alter_column('flashcards', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('flashcards', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_entity_aliases_canonical_name'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_alias_name'), table_name='entity_aliases')
    op.create_index(op.f('idx_entity_aliases_user_id'), 'entity_aliases', ['user_id'], unique=False)
    op.create_index(op.f('idx_entity_aliases_alias'), 'entity_aliases', ['alias_name'], unique=False)
    op.alter_column('entity_aliases', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('entity_aliases', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index(op.f('idx_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('idx_document_chunks_chunk_index'), 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['document_id'], unique=False)
    # ### end Alembic commands ###
