"""obsidian_graph_integration_enhancements

Revision ID: bc3d261dda6a
Revises: a3d7eef3ffed
Create Date: 2026-04-10 22:11:39.377622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3d261dda6a'
down_revision: Union[str, Sequence[str], None] = 'a3d7eef3ffed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
